//! Bakes wordninja's frequency list into a Rust source file at compile time.
//!
//! The upstream list (data/wordninja_words.txt.gz) is ordered by descending
//! word frequency, and wordninja derives every token's cost purely from its
//! rank in that ordering — so the order must be preserved verbatim here.
//!
//! The proper-noun list is deliberately *not* handled here. It is plain text,
//! so it goes in via `include_str!`, and a user's own list is read at run time;
//! both share one parser in src/main.rs.

use std::env;
use std::fs;
use std::io::Read;
use std::path::Path;

fn main() {
    let gz_path = Path::new("data/wordninja_words.txt.gz");
    println!("cargo:rerun-if-changed={}", gz_path.display());

    let compressed = fs::read(gz_path).expect("read data/wordninja_words.txt.gz");
    let mut text = String::new();
    flate2::read::GzDecoder::new(&compressed[..])
        .read_to_string(&mut text)
        .expect("gunzip word list");

    let words: Vec<&str> = text.split_whitespace().collect();
    assert!(!words.is_empty(), "word list is empty");

    // wordninja: maxword = max(len(x) for x in words)
    let max_word_len = words
        .iter()
        .map(|w| w.chars().count())
        .max()
        .expect("non-empty");

    // One string literal keeps rustc happy: {:?} escapes the newlines for us.
    let blob = words.join("\n");

    let generated = format!(
        "// Generated by build.rs from data/wordninja_words.txt.gz — do not edit.\n\
         pub static MAX_WORD_LEN: usize = {};\n\
         pub static WORDS_BLOB: &str = {:?};\n",
        max_word_len, blob,
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("wordlist.rs"), generated).expect("write wordlist.rs");
}
